project:
  type: book

book:
  title: "*Pr&auml;gnanz* in visual perception"
  output-file: "doctoralthesis_EVG"
  subtitle: "Towards better theories, measures, and tests of <i>good Gestalts</i></br></br>  ![&copy; Joris Snaet](chapterfigs/0.png){width=100%}  "
  author: "Eline Van Geert"
  logo: figs/examplefig.png
  date: "02/10/2023"
  page-footer:
    left: "Copyright 2023, Eline Van Geert"
  repo-url: https://github.com/
  downloads: [pdf]
  sharing: [twitter]
  chapters:
    - index.qmd
    - part: part_introduction.qmd
      chapters: 
        - intro.qmd
    - part: part_review.qmd
      chapters: 
        - review.qmd
    - part: part_robustsens.qmd
      chapters: 
        - refpoints.qmd
    - part: part_hystadapt.qmd
      chapters: 
        - rrdotlattices.qmd
    - part: part_ordcompl.qmd
      chapters: 
        - octatoolbox.qmd
    - part: part_simplcompl.qmd
      chapters: 
        - simplcompl.qmd
    - part: part_conclusion.qmd
      chapters: 
        - conclusion.qmd
  appendices: 
    - references.qmd
    - dissemination.qmd
    - app_review.qmd
    - app_refpoints.qmd
    - app_rrdotlattices.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    cover-image: figs/examplefig.png
  pdf:
    pdf-engine: pdflatex
    documentclass: book
    papersize: a4paper
    geometry: margin=1in
    include-before-body: 
      - beforebody.tex
    include-in-header: 
      - preamble.tex


editor: source

