::: {.content-visible when-format="html"}
# Summary {.unnumbered }

Things look as they do, not only because of the visual input an individual receives, but also because of the way in which the viewer organizes the input in a specific context (cf. [Chapter @sec-introduction]). The law of *Prägnanz* states that psycho-physical organization will always be as 'good' as possible given the prevailing circumstances. What does it mean for an organization to be 'good', however, and how do viewers clarify the incoming visual stimuli to achieve the best possible percept? 

A 'good' psycho-physical organization will contain at least some form of unity or regularity, and will become better when it is autonomous, complete, simple of structure, element rich, expressive, and/or meaningful (cf. [Chapter @sec-pragnanzreview]). Prägnanz thus not only deals with purely figural aspects, but also with how purely and compellingly the phenomenal structure embodies an essence. Moreover, it comprises aspects related to both order and complexity. 

To achieve the best or clearest overall organization possible, human perceivers use *internal representations of good Gestalts as reference points* to clarify the visual input. Whereas sometimes these reference points lead to increased *sensitivity to change*, they can also act as robust magnets, decreasing perceptual distance between neighboring stimuli. In a first empirical study (cf. [Chapter @sec-refpoints]), we show how the existence of strong internal reference points can explain differences in categorization, discrimination, and similarity judgments across a series of figures gradually transforming from one recognizable shape to another. 

If no strong pre-existing reference points are available that are similar enough to the incoming visual stimuli, the *immediate context* can play a more extensive role in disambiguating the visual input. In a Registered Report using multistable dot lattices as stimuli (cf. [Chapter @sec-rrdotlattices]), we confirmed differences in how individuals combine previous input and experience with current input in their perception, and showed stability of these individual differences over one to two weeks’ time. Furthermore, we developed an efficient Bayesian observer model that can predict both the *attractive and repulsive* immediate context effects found in this task (cf. [Chapter @sec-effbayesianmodel]).

*How* will the internal reference points or the immediate context be used to clarify the incoming visual stimuli and arrive at a clearer, more prägnant percept? In every perceptual event, both simplification and complication will occur, albeit to a different extent depending on the strength of the internal and external conditions (related to the viewer and the visual input, resp.). Whereas unnecessary details, differentiating the visual input from the point of comparison, will be leveled or removed, important characteristics distinguishing the input from the reference will be emphasized. As we can conclude from our research, however, *which* characteristics will be either superfluous or essential, and as a consequence which characteristics will be either *simplified or complicated*, will partially depend on the context in which the stimulus is presented (cf. [Chapter @sec-simplcompl]).

*Order and complexity* are not only important aspects of Prägnanz, they also contribute to our experience of aesthetic appreciation. To improve reproducibility of research assessing the relation between order, complexity, and aesthetic appreciation in the visual modality, we developed the Order & Complexity Toolbox for Aesthetics (OCTA; cf. [Chapter @sec-octatoolbox]), a Python package and online application focused on creating multi-element displays varying on different order and complexity dimensions (e.g., shape, color, size of elements). Although primarily focused on aesthetics, OCTA can also be used in research on perceptual organization. Some first empirical studies using OCTA stimuli (not part of this dissertation) teach us that whereas order is almost never disfavored, the appreciation of complexity is more context-dependent. This relates closely to the core of Prägnanz: as some form of regularity is always required, how much intricacy a viewer can handle differs between contexts and individuals.

In sum (cf. [Chapter @sec-conclusion]), to clarify and aesthetically evaluate visual stimuli, tendencies are at work that are both antagonistic and complementary: although they tend to decrease each other's influence, they also work together towards a better perceptual organization. What the optimal balance of both tendencies entails exactly will depend on the input the individual receives, the individual in question, the context in which the individual receives the input, as well as their interactions.
:::