::: {.content-visible when-format="html"}
# Samenvatting {.unnumbered}

Dingen zien er niet alleen uit zoals ze eruitzien vanwege de visuele input die een individu ontvangt, maar ook vanwege de manier waarop de kijker deze input in een specifieke context organiseert (cf. [Hoofdstuk @sec-introduction]). De wet van *Prägnanz* stelt dat psycho-fysische organisatie altijd zo 'goed' als mogelijk zal zijn gegeven de heersende omstandigheden. Wat betekent het echter voor een organisatie om 'goed' te zijn, en hoe verduidelijken kijkers de binnenkomende visuele prikkels om tot de best mogelijke waarneming ervan te komen?

Een 'goede' psycho-fysische organisatie zal op z’n minst een vorm van eenheid of regelmaat bevatten, en wordt beter wanneer ze daarnaast ook autonoom, volledig, eenvoudig van structuur, rijk aan elementen, expressief en/of betekenisvol is (cf. [Hoofdstuk @sec-pragnanzreview]). Prägnanz gaat dus niet alleen over puur vormelijke aspecten, maar ook over hoe puur en overtuigend de waargenomen structuur een essentie belichaamt. Bovendien omvat Prägnanz zowel aspecten gerelateerd aan orde als aspecten gerelateerd aan complexiteit. 

Om tot de beste of duidelijkste overkoepelende organisatie mogelijk te komen, gebruiken menselijke waarnemers *interne voorstellingen van goede Gestalten als referentiepunten*, om zo de binnenkomende visuele prikkels te verduidelijken. Alhoewel deze referentiepunten soms leiden tot een verhoogde *sensitiviteit voor verandering*, kunnen ze ook als robuuste magneten functioneren door het waargenomen verschil tussen naburige stimuli te verkleinen. In een eerste empirische studie (cf. [Hoofdstuk @sec-refpoints]) tonen we hoe het bestaan van sterke interne referentiepunten verschillen kan verklaren in categorisatie-, discriminatie-, en similariteitsbeoordelingen over een reeks van figuren die gradueel van een herkenbare naar een andere herkenbare figuur transformeren. 

Als er geen sterke reeds bestaande referentiepunten beschikbaar zijn die voldoende lijken op de binnenkomende visuele prikkels, dan kan de *onmiddellijke context* een belangrijkere rol gaan spelen in het disambigueren van de visuele input. In een Gepreregistreerd Rapport dat gebruik maakt van multistabiele stippenrasters als stimuli (cf. [Hoofdstuk @sec-rrdotlattices]), bevestigden we verschillen in hoe individuen voorafgaande input en ervaring in hun waarneming combineren met de huidige input. Verder toonden we aan dat deze individuele verschillen stabiel bleven over één tot twee weken tijd. Daarnaast ontwikkelden we een efficiënte Bayesiaanse waarnemersmodel dat zowel de *aantrekkende* als *afstotende* effecten van de onmiddellijke context kon voorspellen die we in deze taak vonden (cf. [Hoofdstuk @sec-effbayesianmodel]).

*Hoe* gaan we de interne referentiepunten of onmiddellijke context dan gebruiken om de binnenkomende visuele prikkels te verduidelijken en zo een duidelijker, meer prägnante waarneming te bekomen? In elke perceptuele handeling zullen zowel simplificatie als complicatie voorkomen, al zij het in verschillende mate afhankelijk van de sterkte van de interne en externe omstandigheden (resp. gerelateerd aan de kijker en de visuele input). Terwijl onnodige details waarin de visuele input verschilt van het vergelijkingspunt afgezwakt of verwijderd zullen worden, zullen belangrijke kenmerken die de visuele input onderscheiden van de referentie net benadrukt of uitvergroot worden. Zoals we echter kunnen besluiten uit ons onderzoek: *welke* kenmerken overbodig of net essentieel zullen zijn, en als gevolg daarvan welke kenmerken *gesimplificeerd of gecompliceerd* zullen worden, zal gedeeltelijk afhangen van de context waarin de stimulus wordt aangeboden (cf. [Hoofdstuk @sec-simplcompl]).  

*Orde en complexiteit* zijn niet alleen belangrijke aspecten van Prägnanz, ze dragen ook bij aan het ervaren van esthetische appreciatie. Om de reproduceerbaarheid te verbeteren van onderzoek dat de relatie tussen orde, complexiteit, en esthetische appreciatie bestudeert in de visuele modaliteit, hebben we de Orde & Complexiteits-Toolbox voor Esthetiek (OCTA; cf. [Hoofdstuk @sec-octatoolbox]) ontwikkeld, een Pythonpakket en online applicatie die focussen op de creatie van multi-elementdisplays die variëren op verschillende orde- en complexiteitsdimensies (bijvoorbeeld vorm, kleur, grootte van de elementen). Hoewel de tool voornamelijk gecreëerd is voor toepassing binnen de esthetiek, kan OCTA ook gebruikt worden in onderzoek over perceptuele organisatie. Een aantal eerste empirische studies die OCTA stimuli gebruiken (die geen deel uitmaken van dit doctoraat) leren ons dat hoewel orde bijna nooit wordt afgekeurd, de appreciatie van complexiteit meer contextafhankelijk is. Dit sluit sterk aan bij de kern van Prägnanz: waar enige vorm van regelmaat een algemene vereiste is, verschilt de mate van complexiteit die een kijker aankan tussen contexten en individuen.

Over het algemeen (cf. [Hoofdstuk @sec-conclusion]) kunnen we dus stellen dat er, om de visuele input te verduidelijken en esthetisch the evalueren, tendensen aan het werk zijn die zowel antagonistisch als complementair zijn: hoewel ze elkaars invloed verminderen, werken ze samen toe naar een betere perceptuele organisatie. Waar het optimale evenwichtspunt ligt zal afhankelijk zijn van de input die het individu binnenkrijgt, het individu in kwestie, de context waarin het individu deze input ontvangt, alsook hun interacties.
:::